print("Hi, my name is RudeAI.")
print("I'd like to ask you a few questions.")      
name = input("What is your name?")
print(name,".Why would anyone name a baby that?!")
num1 = int (input("How old are you?"))
print("I think" ,num1, "is a little too old!")
fun = input("What do you do for fun?")
print(fun,"?? That is so lame!")
music = input(" What kind of music do you like?")
print("You must have a sad life, listening to",music,".")
siblings = input("How many siblings do you have?")
print("Only",siblings,"? I have 50")
job = input("What do you want to be when you grow up?")
print(,job,"? Haha, that's the worst job ever!")

